name: Run Football Quant
on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute script
        run: python main.py

      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: data-output
          path: football_result.csv
